# Generated by Django 4.1.2 on 2022-10-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(default=None, max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("A", "Android"), ("I", "iOS")],
                        default=None,
                        max_length=1,
                    ),
                ),
                ("last_push_about_update", models.IntegerField(default=0)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("push_failure", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["type"], name="device_type"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["token"], name="device_token"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["type", "token"], name="device_type_and_token"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["type", "token", "last_push_about_update"],
                name="type_token_last_push",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="device",
            unique_together={("type", "token")},
        ),
    ]
